ALTER TABLE deudas
  ADD COLUMN IF NOT EXISTS valor_total DECIMAL(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS saldo_pendiente DECIMAL(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS plazo_meses INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS valor_cuota DECIMAL(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fecha_corte VARCHAR(10) DEFAULT '',
  ADD COLUMN IF NOT EXISTS fecha_pago VARCHAR(10) DEFAULT '',
  ADD COLUMN IF NOT EXISTS tasa_interes DECIMAL(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cuotas_pagas INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cuotas_faltantes INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS valor_polizas DECIMAL(12,2) DEFAULT 0;
